title: Abella
email: getabullaothow@gmail.com
description: Data Analytics
author: Abella
baseurl: ""
url: "https://kogilo.github.io"

# Social Profiles
twitter_username: AbelOthow #SBootstrap
github_username: kogilo #StartBootstrap
facebook_username: abela.othow/ #StartBootstrap
instagram_username:
linkedin_username: linkedin.com/in/abulla

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

